// Writes src/cards.gen.ts: the practice cards' files (frontend/src/practice/cards),
// so the Worker knows which card ids, versions and topics exist when it
// stores reviews (a card names its topics). The Worker reads them with
// frontend/src/learn/cards.ts, as the practice page does. tags.json and ids.lock
// stay out: the check needs them, the API does not.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('../../frontend/src/practice/cards/', import.meta.url).pathname;
const files = {};
for (const topic of readdirSync(root).sort()) {
  const folder = join(root, topic);
  if (!statSync(folder).isDirectory()) continue;
  for (const name of readdirSync(folder).sort()) if (name.endsWith('.md')) files[`${topic}/${name}`] = readFileSync(join(folder, name), 'utf8');
}
writeFileSync(
  new URL('../src/cards.gen.ts', import.meta.url),
  `// Generated by scripts/cards.mjs from frontend/src/practice/cards; do not edit.\n` +
    `export const cardFiles: Record<string, string> = ${JSON.stringify(files, null, 2)};\n`,
);
