// Writes src/game.gen.ts: the content of Scale or Fail
// (frontend/src/game/content), which the Worker reads with
// frontend/src/game/engine/content.ts to replay runs. The scripted runs
// (reference.json, wrong/) stay out: the checks need them, the API does not.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = new URL('../../frontend/src/game/content/', import.meta.url).pathname;
const files = {};
const walk = (dir) => {
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      if (name !== 'wrong') walk(full);
    } else if ((name.endsWith('.md') || name.endsWith('.json')) && name !== 'reference.json') files[relative(root, full)] = readFileSync(full, 'utf8');
  }
};
walk(root);
writeFileSync(
  new URL('../src/game.gen.ts', import.meta.url),
  `// Generated by scripts/game.mjs from frontend/src/game/content; do not edit.\n` + `export const gameFiles: Record<string, string> = ${JSON.stringify(files, null, 2)};\n`,
);
