// Writes src/problems.gen.ts: every practice problem folder's files, so the
// Worker can verify solutions against the same problems the practice page
// shows (the page gets them from Vite's import.meta.glob instead).
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('../../frontend/src/practice/problems/', import.meta.url).pathname;
const problems = {};
for (const id of readdirSync(root).sort()) {
  const folder = join(root, id);
  if (!statSync(folder).isDirectory()) continue;
  const files = {};
  const read = (dir, prefix) => {
    for (const name of readdirSync(dir).sort()) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) read(path, `${prefix}${name}/`);
      else files[`${prefix}${name}`] = readFileSync(path, 'utf8');
    }
  };
  read(folder, '');
  problems[id] = files;
}
writeFileSync(
  new URL('../src/problems.gen.ts', import.meta.url),
  `// Generated by scripts/problems.mjs from frontend/src/practice/problems; do not edit.\n` +
    `export const problemFolders: Record<string, Record<string, string>> = ${JSON.stringify(problems, null, 2)};\n`,
);
